---
abstract: 'The Specification of the MetaPOD format'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Module::Build: '0.4220'
  Test::More: '1.302073'
  perl: '5.008'
configure_requires:
  Module::Build: '0.4220'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MetaPOD-Spec
provides:
  MetaPOD::JSON:
    file: lib/MetaPOD/JSON.pm
    version: v0.4.2
  MetaPOD::Spec:
    file: lib/MetaPOD/Spec.pm
    version: v0.4.2
requires:
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/MetaPOD-Spec/issues
  homepage: https://github.com/kentnl/MetaPOD-Spec
  repository: https://github.com/kentnl/MetaPOD-Spec.git
version: v0.4.2
